// Generated by Wrangler by running `wrangler types`

interface Env {
	WEB_APP_URL: "https://t.me/DEVumridesbot/pickadatedev";
	BOT_INFO: "{\n    \"id\": 6981308574,\n    \"is_bot\": true,\n    \"first_name\": \"TestingBot\",\n    \"username\": \"DEVumridesbot\",\n    \"can_join_groups\": true,\n    \"can_read_all_group_messages\": false,\n    \"supports_inline_queries\": false,\n    \"can_connect_to_business\": false,\n    \"has_main_web_app\": true\n}";
	BOT_TOKEN: string;
	SOCKET_OBJECT: DurableObjectNamespace<import("./src/index").SocketObject>;
	ASSETS: Fetcher;
}
